spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/spring_demo_bd
    username: elhadjamadoudiallo
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

